export default function BugReportTabEn() {
  return (
    <article>
      <h1>Report a Bug</h1>
      <p>
        Thank you for helping improve the application. A good bug report includes the shareable URL (encoded parameters), a screenshot,
        and if possible an in-situ photo showing the discrepancy.
      </p>

      <h2>Steps</h2>
      <ol>
        <li>
          Open a ticket: <a href="https://github.com/antoine-paris/spaceview/issues" target="_blank" rel="noopener noreferrer">New GitHub issue</a>.
        </li>
        <li>
          Describe the context: browser (version), OS, device, window size or device pixel ratio if relevant.
        </li>
        <li>
          Attach the application screenshot (camera button) and, if possible, a corresponding photo of the sky.
        </li>
        <li>
          Include the sharing URL generated by the app (it encodes location, UTC date/time, view, options).
        </li>
        <li>
          Specify the steps to reproduce the issue (location, time, enabled options).
        </li>
      </ol>

      <h2>Tips</h2>
      <ul>
        <li>Check the UTC time and timezone of the chosen location to avoid DST confusion.</li>
        <li>Indicate if refraction was enabled and the object's altitude (effects are sensitive near the horizon).</li>
      </ul>
    </article>
  );
}